[project]
name = "slack-github-triager-cli"
version = "0.1.0"
description = "CLI for Slack-GitHub triaging tool"
authors = [{name = "Eli Block", email = "3347571+eliblock@users.noreply.github.com"}]
license = {text = "MIT"}
requires-python = ">=3.11"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "click>=8.1.7",
    "selenium>=4.16.0",
    "slack-github-triager-core",
]

[project.scripts]
triager = "slack_github_triager_cli.cli:cli"

[project.optional-dependencies]
dev = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
slack-github-triager-core = { workspace = true }
